### PR TITLE
Update framework version and dependencies

### PR DESCRIPTION
**Pull request by EfimenkoAndrew**
Updated .NET Framework version to 4.6.1 
Updated dependencies 
@msftgits @zmarty 
Please let me know if you mind me to port this lib to .NET standard 2.0 (this will at least enable me to use it for my pet project)
Thank you for your attention.

### CODE REVIEW

**Comment by zmarty** [comment]
Thanks for your contribution! Yes, switching to .NET standard would be great! Do you want to send a PR for that?

**Comment by EfimenkoAndrew** [comment]
@zmarty I think it is better to create different PR for this purpose 
1) it will generate a NuGet package with a minor version change 
2) those who want to link a lib to .net 4.8 - will be able to do that.
Two different PRs will enable more cases for those who create a project that has no .net Standard 2.1 support (my dream - to port this lib to .net standard 2.1, but first to port to 2.0 of course)

**Comment by EfimenkoAndrew** [comment]
@zmarty 
Do you want me to migrate to .net standard in this PR? I can do that on weekends. But it will take some time.

**Comment by EfimenkoAndrew** [comment]
That was a huge struggle but I managed to port to .net standard 2.0. I think there is no need to port to standard 2.1. If you like everything - feel free to merge PR. 
@zmarty @msftgits

**Comment by EfimenkoAndrew** [comment]
Do not merge. I have forgotten to change nuget configuration. Will do that tomorrow (my timezone is GMT+2)

**Comment by zmarty** [comment]
Thank you very much! Will wait.

**Comment by EfimenkoAndrew** [comment]
@zmarty Hi
Fixed everything for travis ci and NuGet 
please take a look and feel free to marge

**Comment by EfimenkoAndrew** [comment]
@zmarty @msftgits Please let me know if there is anything that is required to be done for this PR to be merged.

**Comment by zmarty** [comment]
Looking

**Comment by zmarty** [comment]
Thank you, merged!

@EfimenkoAndrew Can you please check why I cannot run the unit tests from Visual Studio Test Explorer?

image

**Comment by EfimenkoAndrew** [comment]
@zmarty I am usually running ReSharper and it works fine

**Comment by EfimenkoAndrew** [comment]
@zmarty @msftgits 
Did some investigation 
I will add NUnit adapter to enable running tests in MS Test explorer. I use ReSharper so missed this point for MS Tests runner. This/next evening I will create new PR with a fix.

**Pull request merged**
